- name: Get registered VM list
  shell: cat /etc/pve/.vmlist
  register: rawVmList

- name: Get VM list
  set_fact:
    vmList: "{{ rawVmList.stdout | from_json | json_query('ids') }}"

- name: Extract IDs
  set_fact:
    vmListIds: "{{ vmListIds | default([]) + [item.key] }}"
  with_dict: "{{ vmList }}"

- name: Add VMs to HA manager
  shell: "ha-manager add vm:{{ item }} --state started"
  with_items: "{{ vmListIds }}"
  ignore_errors: yes
  run_once: yes
