- name: Install gluster
  apt:
    name: glusterfs-server
    state: present

- name: Start service glusterd, if not started
  service:
    name: glusterd
    state: started
    enabled: yes

- name: Probe peers
  shell: gluster peer probe {{ item }}
  with_items: "{{play_hosts}}"
  ignore_errors: yes

- name: Create brick directory
  file:
    path: /data/brick1/gv0
    state: directory

- name: Prepare replicas
  set_fact:
    replicas: "{{ replicas | default([]) + [item + ':/data/brick1/gv0'] }}"
  with_items: "{{ play_hosts }}"

- name: Create gluster volume
  shell: "gluster volume create gv0 replica {{ play_hosts | length }} {{ replicas | join(' ') }} force"
  run_once: true
  ignore_errors: yes

- name: Free space
  shell: "gluster volume set gv0 cluster.min-free-disk 90%"
  run_once: true

- name: Start gluster volume
  shell: "gluster volume start gv0"
  run_once: true
  ignore_errors: yes

- name: Add gluster volume
  shell: "pvesm add --content iso,snippets,vztmpl,backup,images --volume gv0 --server {{ play_hosts | first }} --server2 {{ play_hosts | last }} glusterfs gluster"
  run_once: true
  ignore_errors: yes
